# build stage

FROM node:12-stretch AS build

WORKDIR /build

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

# runtime stage

FROM alpine:3.10

RUN apk add --update nodejs npm

RUN addgroup -S node && adduser -S node -G node 

USER node

RUN mkdir /home/node/code

WORKDIR /home/node/code

COPY --from=build --chown=node:node /build .

# COPY --chown=node:node . .

EXPOSE 3000

CMD ["node", "index.js"]